### ISSUE TITLE
'bem create' throws an error

### ISSUE THREAD

**Issue by ivitivan** [bem/project-stub#113]
Hi!

`bem create -l desktop.bundles/ -b test` throws an error:

```
Error: level module /tmp/project-stub/.bem/levels/bundles.js can not be found but required by the level /tmp/project-stub/desktop.bundles/.bem/level.js

    at getLevelClass (/tmp/project-stub/node_modules/bem/lib/level.js:30:19)
    at getLevelClass (/tmp/project-stub/node_modules/bem/lib/level.js:48:39)
    at Object.exports.createLevel (/tmp/project-stub/node_modules/bem/lib/level.js:96:18)
    at Opt._val (/tmp/project-stub/node_modules/bem/lib/util.js:65:62)
    at Opt.exports.Opt.Opt._saveVal (/tmp/project-stub/node_modules/bem/node_modules/coa/lib/opt.js:260:18)
    at Opt.exports.Opt.Opt._parse (/tmp/project-stub/node_modules/bem/node_modules/coa/lib/opt.js:271:17)
    at Cmd.exports.Cmd.Cmd._parseOptsAndArgs (/tmp/project-stub/node_modules/bem/node_modules/coa/lib/cmd.js:397:38)
    at /tmp/project-stub/node_modules/bem/node_modules/coa/lib/cmd.js:466:27
    at _fulfilled (/tmp/project-stub/node_modules/bem/node_modules/coa/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/tmp/project-stub/node_modules/bem/node_modules/coa/node_modules/q/q.js:863:30)
```

The same error with the level `desktop.blocks`
The file `project-stub/.bem/levels/bundles.js` is in his place.

**Comment by tadatuta** [comment]
Hi!

Thank you for report!
Can you please give a try to a branch with the fix: https://github.com/bem/project-stub/tree/removeBemEnvironRests ?

**Comment by tadatuta** [comment]
Should be fixed in https://github.com/bem/project-stub/pull/114
