### ISSUE TITLE
Error: Cannot find module 'ym'

### ISSUE THREAD

**Issue by wKich** [bem/project-stub#132]
How to reproduce:

```
$ git clone https://github.com/bem/project-stub.git
$ cd project-stub
$ npm install
$ ./node_modules/.bin/bem create -b 'foo-bar' -l desktop.blocks
Error: Cannot find module 'ym'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.require.resolve (internal/module.js:16:19)
    at Object.<anonymous> (./project-stub/libs/bem-core/.bem/techs/vanilla.js.js:4:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at exports.getTechClass (./project-stub/node_modules/bem/lib/tech/index.js:24:48)
    at exports.getTechClass (./project-stub/node_modules/bem/lib/tech/index.js:42:25)
    at exports.createTech (./project-stub/node_modules/bem/lib/tech/index.js:81:21)
    at Object.exports.Context.INHERIT.createTech (./project-stub/node_modules/bem/lib/context.js:46:16)
    at Object.exports.Context.INHERIT.getTech (./project-stub/node_modules/bem/lib/context.js:40:43)
    at ./project-stub/node_modules/bem/lib/commands/create.js:118:40
    at Array.map (native)
    at ./project-stub/node_modules/bem/lib/commands/create.js:117:40
    at Array.map (native)
    at Cmd.<anonymous> (./project-stub/node_modules/bem/lib/commands/create.js:116:32)
    at ./project-stub/node_modules/bem/node_modules/coa/lib/cmd.js:483:22
    at _fulfilled (./project-stub/node_modules/bem/node_modules/coa/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (./project-stub/node_modules/bem/node_modules/coa/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (./project-stub/node_modules/bem/node_modules/coa/node_modules/q/q.js:796:13)
    at ./project-stub/node_modules/bem/node_modules/coa/node_modules/q/q.js:604:44
    at runSingle (./project-stub/node_modules/bem/node_modules/coa/node_modules/q/q.js:137:13)
    at flush (./project-stub/node_modules/bem/node_modules/coa/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
```

Node.js - 4.2.6
npm - 2.14.12

**Comment by tadatuta** [comment]
@wKich Thank you for report!

We're working on new `bem create` tools from scratch now. Until it's released please install all needed npm dependencies locally (`npm i ym --save-dev`).

**Comment by tadatuta** [comment]
Fixed with `bem-tools` update in https://github.com/bem/project-stub/commit/caf35d075fe38c6f97b1bb3057b93a22d316f2f4
