### ISSUE TITLE
отсутствуют common.blocks и desktop.blocks

### ISSUE THREAD

**Issue by belozer** [bem/project-stub#194]
При попытке запуска через gulp или npm start всё падает..
```
~/sandbox/project-stub on ⭠ master! ⌚ 15:28:55
$ gulp     
[15:29:05] Using gulpfile ~/sandbox/project-stub/gulpfile.js
[15:29:05] Starting 'default'...
[15:29:05] Starting 'build'...
{ Error: ENOENT: no such file or directory, scandir 'common.blocks'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'common.blocks' }
[15:29:05] The following tasks did not complete: default, build
[15:29:05] Did you forget to signal async completion?
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir 'desktop.blocks'
    at Error (native)
```

**Comment by belozer** [comment]
после добавления этих каталогов появляется новая ошибка

```
~/sandbox/project-stub on ⭠ master! ⌚ 15:36:42
$ gulp   
[15:36:47] Using gulpfile ~/sandbox/project-stub/gulpfile.js
[15:36:47] Starting 'default'...
[15:36:47] Starting 'build'...
{ AssertionError: Declaration required to harvest some entities
    at src (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-src/index.js:46:5)
    at BemBundle.Object.assign.src (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:53:28)
    at bundler.pipe.builder.css.bundle (/home/sergey/sandbox/project-stub/gulpfile.js:46:24)
    at tryCatch (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:93:47)
    at tryCatch (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:137:16)
    at Object.keys.map.target (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:93:32)
    at Array.map (native)
    at DestroyableTransform._transform (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:91:40)
    at DestroyableTransform.Transform._read (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
  name: 'AssertionError',
  actual: 0,
  expected: true,
  operator: '==',
  message: 'Declaration required to harvest some entities',
  generatedMessage: false }
Error: no writecb in Transform class
    at afterTransform (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:74:40)
    at TransformState.afterTransform (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at tryCatch (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:139:9)
    at Object.keys.map.target (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:93:32)
    at Array.map (native)
    at DestroyableTransform._transform (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:91:40)
    at DestroyableTransform.Transform._read (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
Error: no writecb in Transform class
    at afterTransform (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:74:40)
    at TransformState.afterTransform (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at tryCatch (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:139:9)
    at Object.keys.map.target (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:93:32)
    at Array.map (native)
    at DestroyableTransform._transform (/home/sergey/sandbox/project-stub/node_modules/gulp-bem-bundle-builder/lib/index.js:91:40)
    at DestroyableTransform.Transform._read (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
Error: no writecb in Transform class
    at afterTransform (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:74:40)
    at DestroyableTransform.TransformState.afterTransform (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at emitOne (events.js:101:20)
    at DestroyableTransform.emit (events.js:188:7)
    at onwriteError (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:322:10)
    at onwrite (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:339:11)
    at WritableState.onwrite (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:123:5)
    at afterTransform (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:81:3)
    at TransformState.afterTransform (/home/sergey/sandbox/project-stub/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:58:12)
    at /home/sergey/sandbox/project-stub/node_modules/gulp-bem-xjst/index.js:141:9
[15:36:47] The following tasks did not complete: default, build
[15:36:47] Did you forget to signal async completion?

```

**Comment by belozer** [comment]
Проблема в __bemdecl.js__ файле, о котором в readme ничего не указано (что его нужно удалить).

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem/project-stub/commit/108585641b0005c26e0a6c9de2d9cc5710f6ce02
