### ISSUE TITLE
Не собирается gulp-ом

### ISSUE THREAD

**Issue by nicothin** [bem/project-stub#221]
Клонирую репозиторий
Ставлю зависимости `npm`-ом
Файлы не меняю, сразу вызываю `node_modules/.bin/gulp`
Получаю:
```
$ node_modules/.bin/gulp
[19:52:38] Using gulpfile D:\projects\project-stub-original\gulpfile.js
[19:52:39] Starting 'default'...
[19:52:39] Starting 'build'...
TypeError: Cannot read property 'block' of undefined
    at data.forEach.dep (D:\projects\project-stub-original\node_modules\@bem\deps\lib\formats\deps.js\parser.js:29:37)
    at Array.forEach (native)
    at depsData.forEach.record (D:\projects\project-stub-original\node_modules\@bem\deps\lib\formats\deps.js\parser.js:27:14)
    at Array.forEach (native)
    at parse (D:\projects\project-stub-original\node_modules\@bem\deps\lib\formats\deps.js\parser.js:23:14)
    at Promise (D:\projects\project-stub-original\node_modules\@bem\deps\lib\parse.js:11:25)
    at D:\projects\project-stub-original\node_modules\@bem\deps\lib\parse.js:9:16
Error: no writecb in Transform class
    at afterTransform (D:\projects\project-stub-original\node_modules\readable-stream\lib\_stream_transform.js:74:40)
    at DestroyableTransform.TransformState.afterTransform (D:\projects\project-stub-original\node_modules\readable-stream\lib\_stream_transform.js:58:12)
    at emitOne (events.js:101:20)
    at DestroyableTransform.emit (events.js:188:7)
    at reEmitEvt (D:\projects\project-stub-original\node_modules\bubble-stream-error\index.js:8:14)
    at f (D:\projects\project-stub-original\node_modules\once\once.js:25:25)
    at DestroyableTransform.emit (D:\projects\project-stub-original\node_modules\bubble-stream-error\index.js:20:9)
    at Promise.resolve.then.catch.err (D:\projects\project-stub-original\node_modules\gulp-bem-src\index.js:178:20)
Error: no writecb in Transform class
    at afterTransform (D:\projects\project-stub-original\node_modules\readable-stream\lib\_stream_transform.js:74:40)
    at DestroyableTransform.TransformState.afterTransform (D:\projects\project-stub-original\node_modules\readable-stream\lib\_stream_transform.js:58:12)
    at emitOne (events.js:101:20)
    at DestroyableTransform.emit (events.js:188:7)
    at reEmitEvt (D:\projects\project-stub-original\node_modules\bubble-stream-error\index.js:8:14)
    at f (D:\projects\project-stub-original\node_modules\once\once.js:25:25)
    at DestroyableTransform.emit (D:\projects\project-stub-original\node_modules\bubble-stream-error\index.js:20:9)
    at Promise.resolve.then.catch.err (D:\projects\project-stub-original\node_modules\gulp-bem-src\index.js:178:20)
Error: no writecb in Transform class
    at afterTransform (D:\projects\project-stub-original\node_modules\readable-stream\lib\_stream_transform.js:74:40)
    at DestroyableTransform.TransformState.afterTransform (D:\projects\project-stub-original\node_modules\readable-stream\lib\_stream_transform.js:58:12)
    at emitOne (events.js:101:20)
    at DestroyableTransform.emit (events.js:188:7)
    at reEmitEvt (D:\projects\project-stub-original\node_modules\bubble-stream-error\index.js:8:14)
    at f (D:\projects\project-stub-original\node_modules\once\once.js:25:25)
    at DestroyableTransform.emit (D:\projects\project-stub-original\node_modules\bubble-stream-error\index.js:20:9)
    at Promise.resolve.then.catch.err (D:\projects\project-stub-original\node_modules\gulp-bem-src\index.js:178:20)
[19:52:40] The following tasks did not complete: default, build
[19:52:40] Did you forget to signal async completion?
```
windows.
нода v6.9.1
глобально стоит 4й галп

Что я делаю не так?

**Comment by tadatuta** [comment]
У меня не воспроизвелось.

Можешь, пожалуйста, в `D:\projects\project-stub-original\node_modules\@bem\deps\lib\formats\deps.js\parser.js` на 22 строку добавить
```js
require('fs').writeFileSync('dump.json', JSON.stringify(depsData, null, 4));
```
и выложить сюда содержимое полученного `dump.json`?

**Comment by nicothin** [comment]
@tadatuta да я снес все и переставил (и репозиторий, и саму ноду со всеми глобальными зависимостями) и теперь все завелось и работает.
простите за беспокойство.
