### ISSUE TITLE
Ошибка при сборке через gulp

### ISSUE THREAD

**Issue by Aventus** [bem/project-stub#286]
```
{ Error: BEMHTML error: TypeError: Cannot read property 'apply' of undefined
    at D:\OpenServer\domains\bem.local\node_modules\gulp-bem-xjst\lib\gulp-bem-xjst.js:120:31
    at tryCatch (D:\OpenServer\domains\bem.local\node_modules\gulp-bem-xjst\lib\gulp-bem-xjst.js:155:16)
    at D:\OpenServer\domains\bem.local\node_modules\gulp-bem-xjst\lib\gulp-bem-xjst.js:117:32
    at Array.forEach (<anonymous>)
    at D:\OpenServer\domains\bem.local\node_modules\gulp-bem-xjst\lib\gulp-bem-xjst.js:114:33
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'BEMHTML error: TypeError: Cannot read property \'apply\' of undefined',
  name: 'Error',
  stack: 'Error: BEMHTML error: TypeError: Cannot read property \'apply\' of undefined\n    at D:\\OpenServer\\domains\\bem.local\\node_modules\\gulp-bem-xjst\\lib\\gulp-bem-xjst.js:120:31\n    at tryCatch (D:\\OpenServer\\domains\\bem.local\\node_modules\\gulp-bem-xjst\\lib\\gulp-bem-xjst.js:155:16)\n    at D:\\OpenServer\\domains\\bem.local\\node_modules\\gulp-bem-xjst\\lib\\gulp-bem-xjst.js:117:32\n    at Array.forEach (<anonymous>)\n    at D:\\OpenServer\\domains\\bem.local\\node_modules\\gulp-bem-xjst\\lib\\gulp-bem-xjst.js:114:33\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)',
  plugin: 'lib',
  showProperties: true,
  showStack: false }
```

Работает если `gulp-bem-xjst.js:118` заменить на `return file.data.BEMHTML.apply(bemjsonFile.data);`

**Comment by tadatuta** [comment]
@Aventus спасибо, исправлено в https://github.com/bem/project-stub/commit/e6dc5e843981ced24152f4345cf7f45d5a1052db
