### ISSUE TITLE
Mac os x постоянно требует модуль bemhtml.js

### ISSUE THREAD

**Issue by kirill3333** [bem/project-stub#62]
При попытке собрать и запустить тестовый проект http://ru.bem.info/articles/start-with-project-stub/ на команде bem make  или при заходе на тестовую страничку после запуска bem server падает вот с такой ошибкой 

13:13:15.519 - warn: *** HTTP error: 500, Error: Tech module with path '/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/libs/bem-core/.bem/techs/bemhtml.js' not found on require search paths
    at exports.Level.INHERIT.resolveTechPath (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/lib/level.js:280:19)
    at exports.Level.INHERIT.resolveTech (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/lib/level.js:228:25)
    at exports.Level.INHERIT.resolveTechName (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/lib/level.js:244:47)
    at exports.Level.INHERIT.resolveTech (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/lib/level.js:231:25)
    at exports.Level.INHERIT.createTech (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/lib/level.js:206:32)
    at exports.Level.INHERIT.getTech (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/lib/level.js:193:43)
    at null.<anonymous> (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/lib/nodes/bundle.js:64:28)
    at Array.forEach (native)
    at null.<anonymous> (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/lib/nodes/bundle.js:62:29)
    at Promise.apply (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/node_modules/q/q.js:752:41)
    at /Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/node_modules/q/q.js:1337:14
    at flush (/Volumes/Data/Work/antoncars_page/bem2/my-bem-project/node_modules/bem/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)

**Comment by tadatuta** [comment]
не воспроизводится
